#!/bin/bash -eu
#
# OCDEV HELP: Build images and run end-to-end tests

rm -rf ./_output/scripts/test-end-to-end/

findmnt -lo TARGET | grep ^/tmp/openshift/ | xargs -r sudo umount
sudo rm -rf /tmp/openshift /var/lib/origin/openshift.local.pv/registry

for i in docker-builder sti-builder deployer keepalived-ipfailover haproxy-router; do
    docker pull openshift/origin-$i:latest
done
ocdev cluster build-image

docker images --format="{{.Repository}}:{{.Tag}}" |
    sed -n -s 's,^\(\(docker.io/\)\?openshift/origin.*\):latest,\1,p' |
    xargs -r -I {} docker tag {}:latest {}:local-end-to-end
USE_IMAGES='openshift/origin-${component}:local-end-to-end' TAG=local-end-to-end ./hack/test-end-to-end.sh
docker images --format="{{.Repository}}:{{.Tag}}" |
    grep ':local-end-to-end$' |
    xargs -r docker rmi
