#!/bin/sh -eu

NAMESPACE=${OCDEV_NAMESPACE:-$(ocdev current-namespace)}
SERVICE=${OCDEV_SERVICE:-registry}

NAMESPACE=${NAMESPACE:-default}
HOSTNAME="$SERVICE.$NAMESPACE.svc"

oc create secret docker-registry "$SERVICE-$NAMESPACE" --docker-server="$HOSTNAME" --docker-username=admin --docker-password=qwerty
