#!/bin/bash
set -eu

# OCDEV HELP: Check that the cluster is stopped.

if oc status >/dev/null 2>&1; then
    echo "Expected a stopped cluster, but your cluster is running." >&2
    if [ -n "${OCDEV_FORCE_CLUSTER_IS_STOPPED-}" ]; then
        exit 0
    fi
    echo >&2
    echo "You may set the environment variable OCDEV_FORCE_CLUSTER_IS_STOPPED=1 to ignore this check." >&2
    exit 1
fi

exit 0
