#!/bin/bash -eu

IMAGE=$1

cdpkg "github.com/openshift/cluster-image-registry-operator"
oc apply -f ./vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
oc apply -f ./vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
make build-image IMAGE="$IMAGE"
docker push "$IMAGE"
ocdev registry disable-cvo
REF=$(docker inspect "$IMAGE" | jq -r '.[0].RepoDigests[0]')
oc -n openshift-image-registry patch deploy cluster-image-registry-operator -p "$(jq -nc --arg IMAGE "$REF" '{"spec":{"template":{"spec":{"containers":[{"name":"cluster-image-registry-operator","image":$IMAGE}]}}}}')"
