#!/bin/bash -eu

# OCDEV HELP: Make the image registry operator unmanaged by Cluster Version Operator

OVERRIDES=$(kubectl get clusterversion/version -o jsonpath='{.spec.overrides}')
if [ -z "$OVERRIDES" ]; then
    kubectl patch clusterversion version --type json -p '
    - op: replace
      path: /spec/overrides
      value: []
    '
fi

kubectl patch clusterversion version --type json -p '
- op: add
  path: /spec/overrides/-
  value:
    kind: Deployment
    name: cluster-image-registry-operator
    namespace: openshift-image-registry
    unmanaged: true
'
