#!/bin/bash -eu

# OCDEV HELP: Enable the metrics endpoint

ocdefault patch dc docker-registry -p '{"spec": {"template":
  {"spec": {"containers": [{
    "name": "registry",
    "env": [
      {"name": "REGISTRY_OPENSHIFT_METRICS_ENABLED", "value": "true"},
      {"name": "REGISTRY_OPENSHIFT_METRICS_SECRET", "value": "mysecret"}
    ]
  }]}}
}}'
ocdefault rollout status dc/docker-registry
echo
echo 'Done. You can check it using the command:'
echo
echo '  curl -v -H "Authorization: Bearer mysecret" http://172.30.1.1:5000/extensions/v2/metrics'
echo
