#!/bin/bash -eu

# OCDEV HELP: Generate some garbage

REGISTRY=$(ocdefault registry info)

docker-force-pull() {
    docker pull "$1"
    docker rmi -f "$(docker inspect --format="{{.ID}}" "$1")"
    docker pull "$1"
    docker rmi "$1"
}

ocdev login-as-developer
oc project myproject
docker login -u $(oc whoami) -p $(oc whoami -t) $REGISTRY

oc import-image dmage-a --from=dmage/example:a --confirm
docker-force-pull $REGISTRY/myproject/dmage-a
oc import-image dmage-b --from=dmage/example:b --confirm
docker-force-pull $REGISTRY/myproject/dmage-b
oc delete is/dmage-b

docker pull busybox
docker pull busybox:glibc
docker tag busybox $REGISTRY/myproject/busybox
docker push $REGISTRY/myproject/busybox
docker tag busybox:glibc $REGISTRY/myproject/busybox-glibc
docker push $REGISTRY/myproject/busybox-glibc
oc delete is/busybox-glibc
ocdefault delete image $(ocdefault get images | grep -F /myproject/busybox-glibc@ | cut -d' ' -f1)
docker tag busybox $REGISTRY/myproject/busybox-empty
docker push $REGISTRY/myproject/busybox-empty
oc delete istag/busybox-empty:latest
