#!/bin/bash
set -eu

# OCDEV HELP: Run the integration tests

ocdev check cluster-is-running
ocdev login-as-system-admin

cdpkg "$OCDEV_IMAGEREGISTRY_PACKAGE"
TEST_KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}" make test-integration
